### ISSUE TITLE
Add Water Sensors (z-wave)

### ISSUE THREAD

**Issue by tonesto7** [pdlove/homebridge-smartthings#44] opened 2016-02-17 03:10 UTC
My current device is the Everspring model with:
capability "Water Sensor"
capability "Configuration"
capability "Sensor"
capability "Battery"

Thanks again for your efforts.

**Comment by pdlove** [comment] 2016-02-17 23:14
Duplicate of #32 .
It's on my list. I'll be making several custom Services this weekend.

**Closed** 2016-02-17 23:14 UTC
Labels: duplicate
